# Site settings
title: Craft.
author: LynneSS
description: "Keeping track of crafty things."
baseurl: ""
url: http://localhost:4000
date_format: "%-d %b %Y"
meta_robots: noindex

collections:
  projects:
    output: true
  tags:
    output: true

# Build settings
markdown: kramdown
sass:
  compressed: true

exclude: [vendor]

incremental: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "home"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
