# Site settings
title: Craft.
author: LynneSS
description: "Keeping track of crafty things."
baseurl: ""
url: http://localhost:4000
date_format: "%b %-d, %Y"
meta_robots: noindex

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Build settings
markdown: kramdown
paginate: 10
sass:
  compressed: true
gems:
  - jekyll-paginate
  - jekyll-sitemap

exclude: [vendor]
